name: 'Terraform CI/CD'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Adding dummy AWS credentials so terraform plan doesn't fail
env:
  AWS_ACCESS_KEY_ID: "mock_access_key"
  AWS_SECRET_ACCESS_KEY: "mock_secret_key"
  AWS_DEFAULT_REGION: "ap-south-1"

jobs:
  terraform:
    name: 'Terraform Validation & Plan'
    runs-on: ubuntu-latest

    steps:
    # Updated to v4 to fix Node.js 20 deprecation and git exit code 128
    - name: Checkout Code
      uses: actions/checkout@v4

    # Updated to v3 for latest Node.js support
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.0

    - name: Terraform Format
      id: fmt
      run: terraform fmt -recursive
      continue-on-error: true

    - name: Terraform Init (DEV)
      working-directory: infra/envs/dev
      run: terraform init

    - name: Terraform Validate (DEV)
      working-directory: infra/envs/dev
      run: terraform validate

    - name: Terraform Plan (DEV)
      working-directory: infra/envs/dev
      run: terraform plan -refresh=false

    - name: Terraform Init (PROD)
      working-directory: infra/envs/prod
      run: terraform init

    - name: Terraform Validate (PROD)
      working-directory: infra/envs/prod
      run: terraform validate

    - name: Terraform Plan (PROD)
      working-directory: infra/envs/prod
      run: terraform plan -refresh=false